ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "seller1Name" TEXT;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "seller2Name" TEXT;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "agreementDate" TEXT;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "cashAtClosing" TEXT;
